/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/solid-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardChatRouteImport } from './routes/dashboard/chat'
import { Route as DashboardAccountRouteImport } from './routes/dashboard/account'

const ApiAuthCallbackTwitterLazyRouteImport = createFileRoute(
  '/api/auth/callback/twitter',
)()
const ApiAuthCallbackGoogleLazyRouteImport = createFileRoute(
  '/api/auth/callback/google',
)()
const ApiAuthCallbackGithubLazyRouteImport = createFileRoute(
  '/api/auth/callback/github',
)()

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChatRoute = DashboardChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiAuthCallbackTwitterLazyRoute =
  ApiAuthCallbackTwitterLazyRouteImport.update({
    id: '/api/auth/callback/twitter',
    path: '/api/auth/callback/twitter',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/api/auth/callback/twitter.lazy').then((d) => d.Route),
  )
const ApiAuthCallbackGoogleLazyRoute =
  ApiAuthCallbackGoogleLazyRouteImport.update({
    id: '/api/auth/callback/google',
    path: '/api/auth/callback/google',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/api/auth/callback/google.lazy').then((d) => d.Route),
  )
const ApiAuthCallbackGithubLazyRoute =
  ApiAuthCallbackGithubLazyRouteImport.update({
    id: '/api/auth/callback/github',
    path: '/api/auth/callback/github',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/api/auth/callback/github.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/callback/github': typeof ApiAuthCallbackGithubLazyRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleLazyRoute
  '/api/auth/callback/twitter': typeof ApiAuthCallbackTwitterLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/callback/github': typeof ApiAuthCallbackGithubLazyRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleLazyRoute
  '/api/auth/callback/twitter': typeof ApiAuthCallbackTwitterLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/callback/github': typeof ApiAuthCallbackGithubLazyRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleLazyRoute
  '/api/auth/callback/twitter': typeof ApiAuthCallbackTwitterLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/account'
    | '/dashboard/chat'
    | '/dashboard/'
    | '/api/auth/callback/github'
    | '/api/auth/callback/google'
    | '/api/auth/callback/twitter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard/account'
    | '/dashboard/chat'
    | '/dashboard'
    | '/api/auth/callback/github'
    | '/api/auth/callback/google'
    | '/api/auth/callback/twitter'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/account'
    | '/dashboard/chat'
    | '/dashboard/'
    | '/api/auth/callback/github'
    | '/api/auth/callback/google'
    | '/api/auth/callback/twitter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ApiAuthCallbackGithubLazyRoute: typeof ApiAuthCallbackGithubLazyRoute
  ApiAuthCallbackGoogleLazyRoute: typeof ApiAuthCallbackGoogleLazyRoute
  ApiAuthCallbackTwitterLazyRoute: typeof ApiAuthCallbackTwitterLazyRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/chat': {
      id: '/dashboard/chat'
      path: '/chat'
      fullPath: '/dashboard/chat'
      preLoaderRoute: typeof DashboardChatRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/auth/callback/twitter': {
      id: '/api/auth/callback/twitter'
      path: '/api/auth/callback/twitter'
      fullPath: '/api/auth/callback/twitter'
      preLoaderRoute: typeof ApiAuthCallbackTwitterLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback/google': {
      id: '/api/auth/callback/google'
      path: '/api/auth/callback/google'
      fullPath: '/api/auth/callback/google'
      preLoaderRoute: typeof ApiAuthCallbackGoogleLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback/github': {
      id: '/api/auth/callback/github'
      path: '/api/auth/callback/github'
      fullPath: '/api/auth/callback/github'
      preLoaderRoute: typeof ApiAuthCallbackGithubLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardChatRoute: typeof DashboardChatRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardChatRoute: DashboardChatRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ApiAuthCallbackGithubLazyRoute: ApiAuthCallbackGithubLazyRoute,
  ApiAuthCallbackGoogleLazyRoute: ApiAuthCallbackGoogleLazyRoute,
  ApiAuthCallbackTwitterLazyRoute: ApiAuthCallbackTwitterLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
